'use client';

import { Dispatch, ReactNode, SetStateAction, useEffect, useMemo, useState } from 'react';
import { adminApiFetch } from '../../admin-api';
import { AdminBadge, AdminButton, AdminCard, AdminGrid, AdminMetric, AdminMetricGrid, AdminNotice, AdminPage, AdminRow, AdminStack, AdminToolbar } from '../_components/admin-ui';

type CmsContent = {
  banners: Array<{ title: string; subtitle: string; imageUrl: string; href: string; enabled: boolean }>;
  popup: { title: string; message: string; ctaLabel: string; href: string; enabled: boolean; version?: string };
  announcements: Array<{ title: string; message: string; enabled: boolean }>;
  faqs: Array<{ question: string; answer: string; enabled: boolean }>;
};

const defaultContent: CmsContent = {
  banners: [{ title: 'พร้อมเล่นทุกเกม', subtitle: 'ฝาก ถอน เล่นเกม และดูประวัติได้ในมือถือเครื่องเดียว', imageUrl: '', href: '/games', enabled: true }],
  popup: { title: 'ประกาศ', message: 'ยินดีต้อนรับ', ctaLabel: 'ดูเกม', href: '/games', enabled: false, version: 'v1' },
  announcements: [{ title: 'ระบบพร้อมใช้งาน', message: 'ฝาก ถอน และเกมเปิดให้บริการตามปกติ', enabled: true }],
  faqs: [{ question: 'ฝากใช้เวลานานไหม', answer: 'หลังแนบสลิป แอดมินจะตรวจและอนุมัติให้เร็วที่สุด', enabled: true }],
};

export default function ContentCenterPage() {
  const [content, setContent] = useState<CmsContent>(defaultContent);
  const [message, setMessage] = useState('กำลังโหลด CMS...');
  const [saving, setSaving] = useState(false);
  useEffect(() => { load(); }, []);
  const stats = useMemo(() => ({ banners: content.banners.filter((item) => item.enabled).length, announcements: content.announcements.filter((item) => item.enabled).length, faqs: content.faqs.filter((item) => item.enabled).length, popup: content.popup.enabled ? 1 : 0, brokenImages: content.banners.filter((item) => item.imageUrl && !isValidUrl(item.imageUrl)).length }), [content]);
  const warnings = useMemo(() => buildWarnings(content), [content]);
  async function load() { const res = await adminApiFetch('/admin/settings/features'); const data = await res.json().catch(() => null); if (!res.ok) { setMessage(data?.message ?? 'โหลด CMS ไม่สำเร็จ'); return; } setContent(normalizeContent(data?.settings?.cms_content)); setMessage(''); }
  async function save() { setSaving(true); setMessage('กำลังบันทึก CMS...'); const res = await adminApiFetch('/admin/settings/features', { method: 'PUT', body: JSON.stringify({ cms_content: content }) }); const data = await res.json().catch(() => null); setSaving(false); if (!res.ok) { setMessage(data?.message ?? 'บันทึก CMS ไม่สำเร็จ'); return; } setMessage('บันทึก CMS แล้ว'); }
  function resetPopupVersion() { patchPopup({ version: `v${Date.now()}` }, setContent); setMessage('เปลี่ยน popup version แล้ว สมาชิกจะเห็น popup ใหม่หลังบันทึก'); }
  return <AdminPage eyebrow="Content" title="CMS / Banner / Popup" description="จัดการ banner, popup, announcement และ FAQ พร้อม preview มือถือ ก่อนปล่อยให้หน้าแรกกลายเป็นงานศิลปะรูปแตก" actions={<><AdminButton onClick={load} tone="secondary">รีเฟรช</AdminButton><AdminButton onClick={save} disabled={saving}>{saving ? 'กำลังบันทึก...' : 'บันทึก'}</AdminButton></>}>
    {message && <AdminNotice>{message}</AdminNotice>}
    {warnings.length > 0 && <AdminNotice>{warnings.join(' • ')}</AdminNotice>}
    <AdminMetricGrid><AdminMetric tone="success" title="Banner เปิดอยู่" value={String(stats.banners)} helper={`${content.banners.length} รายการ`} /><AdminMetric tone={stats.popup ? 'success' : 'neutral'} title="Popup" value={stats.popup ? 'เปิด' : 'ปิด'} helper={`version ${content.popup.version ?? 'v1'}`} /><AdminMetric tone="success" title="Announcement" value={String(stats.announcements)} helper="ประกาศที่เปิด" /><AdminMetric tone={stats.brokenImages > 0 ? 'danger' : 'neutral'} title="รูปผิดรูปแบบ" value={String(stats.brokenImages)} helper="URL ต้องขึ้นต้น http/https" /></AdminMetricGrid>
    <AdminGrid><AdminCard title="Banner หน้าแรก" tone="success"><AdminStack>{content.banners.map((item, index) => <EditorCard key={index} title={`Banner ${index + 1}`} enabled={item.enabled} onToggle={() => patchBanner(index, { enabled: !item.enabled }, setContent)} onRemove={() => setContent((current) => ({ ...current, banners: current.banners.filter((_, i) => i !== index) }))} onMoveUp={index > 0 ? () => moveItem('banners', index, -1, setContent) : undefined} onMoveDown={index < content.banners.length - 1 ? () => moveItem('banners', index, 1, setContent) : undefined}><Field label="หัวข้อ" value={item.title} onChange={(value) => patchBanner(index, { title: value }, setContent)} /><Field label="ข้อความรอง" value={item.subtitle} onChange={(value) => patchBanner(index, { subtitle: value }, setContent)} /><Field label="ลิงก์รูป" value={item.imageUrl} onChange={(value) => patchBanner(index, { imageUrl: value }, setContent)} warning={item.imageUrl && !isValidUrl(item.imageUrl) ? 'URL รูปไม่ถูกต้อง' : undefined} /><Field label="ลิงก์ปุ่ม" value={item.href} onChange={(value) => patchBanner(index, { href: value }, setContent)} warning={!isSafeHref(item.href) ? 'ลิงก์ควรขึ้นต้น / หรือ http/https' : undefined} /></EditorCard>)}<AdminButton tone="secondary" onClick={() => setContent((current) => ({ ...current, banners: [...current.banners, { title: 'Banner ใหม่', subtitle: '', imageUrl: '', href: '/games', enabled: true }] }))}>เพิ่ม Banner</AdminButton></AdminStack></AdminCard>
    <AdminCard title="Preview มือถือ" description="ดูภาพรวมแบบ member home ย่อส่วน"><MobilePreview content={content} /></AdminCard></AdminGrid>
    <AdminGrid><AdminCard title="Popup" tone={content.popup.enabled ? 'warning' : 'neutral'}><AdminStack><EditorCard title="Popup หลัก" enabled={content.popup.enabled} onToggle={() => setContent((current) => ({ ...current, popup: { ...current.popup, enabled: !current.popup.enabled } }))}><Field label="หัวข้อ" value={content.popup.title} onChange={(value) => patchPopup({ title: value }, setContent)} /><Field label="ข้อความ" value={content.popup.message} onChange={(value) => patchPopup({ message: value }, setContent)} textarea /><Field label="ปุ่ม" value={content.popup.ctaLabel} onChange={(value) => patchPopup({ ctaLabel: value }, setContent)} /><Field label="ลิงก์" value={content.popup.href} onChange={(value) => patchPopup({ href: value }, setContent)} warning={!isSafeHref(content.popup.href) ? 'ลิงก์ควรขึ้นต้น / หรือ http/https' : undefined} /><AdminRow><strong>Version</strong><span>{content.popup.version ?? 'v1'}</span></AdminRow><AdminButton tone="secondary" onClick={resetPopupVersion}>ให้สมาชิกเห็น popup ใหม่อีกครั้ง</AdminButton></EditorCard></AdminStack></AdminCard>
    <AdminCard title="Announcement" tone="warning"><AdminStack>{content.announcements.map((item, index) => <EditorCard key={index} title={`ประกาศ ${index + 1}`} enabled={item.enabled} onToggle={() => patchAnnouncement(index, { enabled: !item.enabled }, setContent)} onRemove={() => setContent((current) => ({ ...current, announcements: current.announcements.filter((_, i) => i !== index) }))} onMoveUp={index > 0 ? () => moveItem('announcements', index, -1, setContent) : undefined} onMoveDown={index < content.announcements.length - 1 ? () => moveItem('announcements', index, 1, setContent) : undefined}><Field label="หัวข้อ" value={item.title} onChange={(value) => patchAnnouncement(index, { title: value }, setContent)} /><Field label="ข้อความ" value={item.message} onChange={(value) => patchAnnouncement(index, { message: value }, setContent)} textarea /></EditorCard>)}<AdminButton tone="secondary" onClick={() => setContent((current) => ({ ...current, announcements: [...current.announcements, { title: 'ประกาศใหม่', message: '', enabled: true }] }))}>เพิ่มประกาศ</AdminButton></AdminStack></AdminCard></AdminGrid>
    <AdminCard title="FAQ" tone="neutral"><AdminStack>{content.faqs.map((item, index) => <EditorCard key={index} title={`FAQ ${index + 1}`} enabled={item.enabled} onToggle={() => patchFaq(index, { enabled: !item.enabled }, setContent)} onRemove={() => setContent((current) => ({ ...current, faqs: current.faqs.filter((_, i) => i !== index) }))} onMoveUp={index > 0 ? () => moveItem('faqs', index, -1, setContent) : undefined} onMoveDown={index < content.faqs.length - 1 ? () => moveItem('faqs', index, 1, setContent) : undefined}><Field label="คำถาม" value={item.question} onChange={(value) => patchFaq(index, { question: value }, setContent)} /><Field label="คำตอบ" value={item.answer} onChange={(value) => patchFaq(index, { answer: value }, setContent)} textarea /></EditorCard>)}<AdminButton tone="secondary" onClick={() => setContent((current) => ({ ...current, faqs: [...current.faqs, { question: 'คำถามใหม่', answer: '', enabled: true }] }))}>เพิ่ม FAQ</AdminButton></AdminStack></AdminCard>
    <AdminToolbar><strong>Preview JSON</strong><span style={mutedStyle}>เก็บใน features.cms_content, public ได้ เพราะไม่ใช่ secret</span></AdminToolbar><pre style={preStyle}>{JSON.stringify(content, null, 2)}</pre>
  </AdminPage>;
}

function EditorCard({ title, enabled, onToggle, onRemove, onMoveUp, onMoveDown, children }: { title: string; enabled: boolean; onToggle: () => void; onRemove?: () => void; onMoveUp?: () => void; onMoveDown?: () => void; children: ReactNode }) { return <div style={editorStyle}><AdminRow><strong>{title}</strong><div style={rowActionsStyle}><AdminBadge tone={enabled ? 'success' : 'neutral'}>{enabled ? 'เปิด' : 'ปิด'}</AdminBadge>{onMoveUp && <AdminButton tone="secondary" onClick={onMoveUp}>ขึ้น</AdminButton>}{onMoveDown && <AdminButton tone="secondary" onClick={onMoveDown}>ลง</AdminButton>}<AdminButton tone="secondary" onClick={onToggle}>{enabled ? 'ปิด' : 'เปิด'}</AdminButton>{onRemove && <AdminButton tone="danger" onClick={onRemove}>ลบ</AdminButton>}</div></AdminRow><div style={fieldGridStyle}>{children}</div></div>; }
function Field({ label, value, onChange, textarea = false, warning }: { label: string; value: string; onChange: (value: string) => void; textarea?: boolean; warning?: string }) { return <label style={fieldStyle}><span>{label}</span>{textarea ? <textarea value={value} onChange={(event) => onChange(event.target.value)} style={textareaStyle} /> : <input value={value} onChange={(event) => onChange(event.target.value)} style={inputStyle} />}{warning && <small style={warningStyle}>{warning}</small>}</label>; }
function MobilePreview({ content }: { content: CmsContent }) { const banner = content.banners.find((item) => item.enabled); const announcements = content.announcements.filter((item) => item.enabled).slice(0, 2); const faqs = content.faqs.filter((item) => item.enabled).slice(0, 2); return <div style={phoneStyle}><div style={phoneTopStyle}>Member preview</div>{banner && <section style={phoneBannerStyle}>{banner.imageUrl && isValidUrl(banner.imageUrl) && <img src={banner.imageUrl} alt="" style={phoneImageStyle} />}<strong>{banner.title || 'Banner'}</strong><span>{banner.subtitle || 'ข้อความรอง'}</span><em>{banner.href || '/games'}</em></section>}{announcements.map((item, index) => <div key={index} style={phoneCardStyle}><strong>{item.title || 'ประกาศ'}</strong><span>{item.message || 'ข้อความประกาศ'}</span></div>)}{faqs.map((item, index) => <div key={index} style={phoneCardStyle}><strong>{item.question || 'คำถาม'}</strong><span>{item.answer || 'คำตอบ'}</span></div>)}{content.popup.enabled && <div style={phonePopupStyle}><strong>{content.popup.title}</strong><span>{content.popup.message}</span><em>{content.popup.ctaLabel}</em></div>}</div>; }
function normalizeContent(value: unknown): CmsContent { const data = value && typeof value === 'object' && !Array.isArray(value) ? value as Partial<CmsContent> : {}; return { banners: Array.isArray(data.banners) ? data.banners.map((item: any) => ({ title: String(item.title ?? ''), subtitle: String(item.subtitle ?? ''), imageUrl: String(item.imageUrl ?? ''), href: String(item.href ?? '/games'), enabled: item.enabled !== false })) : defaultContent.banners, popup: { ...defaultContent.popup, ...(data.popup && typeof data.popup === 'object' ? data.popup : {}) } as CmsContent['popup'], announcements: Array.isArray(data.announcements) ? data.announcements.map((item: any) => ({ title: String(item.title ?? ''), message: String(item.message ?? ''), enabled: item.enabled !== false })) : defaultContent.announcements, faqs: Array.isArray(data.faqs) ? data.faqs.map((item: any) => ({ question: String(item.question ?? ''), answer: String(item.answer ?? ''), enabled: item.enabled !== false })) : defaultContent.faqs }; }
function patchBanner(index: number, patch: Partial<CmsContent['banners'][number]>, setContent: Dispatch<SetStateAction<CmsContent>>) { setContent((current) => ({ ...current, banners: current.banners.map((item, i) => i === index ? { ...item, ...patch } : item) })); }
function patchPopup(patch: Partial<CmsContent['popup']>, setContent: Dispatch<SetStateAction<CmsContent>>) { setContent((current) => ({ ...current, popup: { ...current.popup, ...patch } })); }
function patchAnnouncement(index: number, patch: Partial<CmsContent['announcements'][number]>, setContent: Dispatch<SetStateAction<CmsContent>>) { setContent((current) => ({ ...current, announcements: current.announcements.map((item, i) => i === index ? { ...item, ...patch } : item) })); }
function patchFaq(index: number, patch: Partial<CmsContent['faqs'][number]>, setContent: Dispatch<SetStateAction<CmsContent>>) { setContent((current) => ({ ...current, faqs: current.faqs.map((item, i) => i === index ? { ...item, ...patch } : item) })); }
function moveItem(key: 'banners' | 'announcements' | 'faqs', index: number, direction: -1 | 1, setContent: Dispatch<SetStateAction<CmsContent>>) { setContent((current) => { const list = [...current[key]] as any[]; const target = index + direction; if (target < 0 || target >= list.length) return current; [list[index], list[target]] = [list[target], list[index]]; return { ...current, [key]: list }; }); }
function isValidUrl(value: string) { if (!value) return true; try { const url = new URL(value); return url.protocol === 'http:' || url.protocol === 'https:'; } catch { return false; } }
function isSafeHref(value: string) { return Boolean(value?.startsWith('/') || isValidUrl(value)); }
function buildWarnings(content: CmsContent) { const warnings = []; if (content.banners.some((item) => item.imageUrl && !isValidUrl(item.imageUrl))) warnings.push('มีลิงก์รูป banner ที่ไม่ถูกต้อง'); if (content.banners.some((item) => !item.title.trim() && item.enabled)) warnings.push('มี banner เปิดอยู่แต่ไม่มีหัวข้อ'); if (content.popup.enabled && !content.popup.message.trim()) warnings.push('เปิด popup แต่ยังไม่มีข้อความ'); return warnings; }
const mutedStyle = { color: '#94a3b8' } as const;
const editorStyle = { border: '1px solid rgba(148,163,184,.14)', borderRadius: 16, padding: 12, background: 'rgba(255,255,255,.04)', display: 'grid', gap: 10 } as const;
const rowActionsStyle = { display: 'flex', gap: 8, flexWrap: 'wrap' as const, alignItems: 'center' };
const fieldGridStyle = { display: 'grid', gap: 10 } as const;
const fieldStyle = { display: 'grid', gap: 6, fontWeight: 850 } as const;
const inputStyle = { minHeight: 42, borderRadius: 12, border: '1px solid rgba(148,163,184,.22)', background: '#0b1220', color: '#f8fafc', padding: '0 12px', minWidth: 0 } as const;
const textareaStyle = { ...inputStyle, minHeight: 86, padding: 12, resize: 'vertical' as const };
const warningStyle = { color: '#fca5a5' } as const;
const preStyle = { overflowX: 'auto' as const, whiteSpace: 'pre-wrap' as const, border: '1px solid rgba(148,163,184,.14)', borderRadius: 16, padding: 14, background: '#020617', color: '#cbd5e1' } as const;
const phoneStyle = { width: 'min(330px, 100%)', margin: '0 auto', border: '1px solid rgba(148,163,184,.22)', borderRadius: 30, padding: 14, background: 'linear-gradient(180deg,#080808,#111827)', display: 'grid', gap: 10, minHeight: 560 } as const;
const phoneTopStyle = { textAlign: 'center' as const, color: '#94a3b8', fontSize: 12, fontWeight: 900 };
const phoneBannerStyle = { border: '1px solid rgba(245,197,66,.28)', borderRadius: 20, padding: 12, background: 'rgba(245,197,66,.10)', display: 'grid', gap: 6 } as const;
const phoneImageStyle = { width: '100%', height: 92, objectFit: 'cover' as const, borderRadius: 14 };
const phoneCardStyle = { border: '1px solid rgba(255,255,255,.10)', borderRadius: 16, padding: 12, background: 'rgba(255,255,255,.05)', display: 'grid', gap: 4 } as const;
const phonePopupStyle = { marginTop: 'auto', border: '1px solid rgba(245,197,66,.28)', borderRadius: 18, padding: 12, background: '#111827', display: 'grid', gap: 5 } as const;
